# CMake工具函数

# 打印配置摘要
function(print_configuration_summary)
    message(STATUS "")
    message(STATUS "========================================")
    message(STATUS "  Vulkan Engine Configuration Summary")
    message(STATUS "========================================")
    message(STATUS "")
    message(STATUS "Build Configuration:")
    message(STATUS "  C++ Standard:      ${CMAKE_CXX_STANDARD}")
    message(STATUS "  Build Type:        ${CMAKE_BUILD_TYPE}")
    message(STATUS "  Compiler ID:       ${CMAKE_CXX_COMPILER_ID}")
    message(STATUS "  CMake Version:     ${CMAKE_VERSION}")
    message(STATUS "")
    message(STATUS "Project Options:")
    message(STATUS "  Render Graph:      ${VULKAN_ENGINE_USE_RENDER_GRAPH}")
    message(STATUS "  Async Loading:     ${VULKAN_ENGINE_USE_ASYNC_LOADING}")
    message(STATUS "  Hot Reload:        ${VULKAN_ENGINE_USE_HOT_RELOAD}")
    message(STATUS "  Validation Layers: ${VULKAN_ENGINE_ENABLE_VALIDATION}")
    message(STATUS "  Debug Markers:     ${VULKAN_ENGINE_ENABLE_DEBUG_MARKERS}")
    message(STATUS "")
    message(STATUS "Dependencies:")
    message(STATUS "  Vulkan:            ${Vulkan_FOUND}")
    message(STATUS "  GLFW3:             ${glfw3_FOUND}")
    message(STATUS "  GLM:               ${glm_FOUND}")
    message(STATUS "  STB:               ${stb_FOUND}")
    message(STATUS "  Taskflow:          ${VULKAN_ENGINE_HAS_TASKFLOW}")
    message(STATUS "  VMA:               ${VULKAN_ENGINE_HAS_VMA}")
    message(STATUS "  SPIRV-Tools:       ${VULKAN_ENGINE_HAS_SPIRVTOOLS}")
    message(STATUS "")
    message(STATUS "Performance Options:")
    message(STATUS "  Precompiled Hdrs:  ${VULKAN_ENGINE_ENABLE_PCH}")
    message(STATUS "  LTO:               ${VULKAN_ENGINE_ENABLE_LTO}")
    message(STATUS "  Sanitizers:        ${VULKAN_ENGINE_ENABLE_SANITIZERS}")
    message(STATUS "")
    message(STATUS "Static Analysis:")
    message(STATUS "  Clang-Tidy:        ${VULKAN_ENGINE_ENABLE_CLANG_TIDY}")
    message(STATUS "  Cppcheck:          ${VULKAN_ENGINE_ENABLE_CPPCHECK}")
    message(STATUS "")
    message(STATUS "========================================")
    message(STATUS "")
endfunction()

# 获取当前目录下所有子目录
function(get_subdirectories result curdir)
    file(GLOB children RELATIVE ${curdir} ${curdir}/*)
    set(dirlist "")
    foreach (child ${children})
        if (IS_DIRECTORY ${curdir}/${child})
            list(APPEND dirlist ${child})
        endif ()
    endforeach ()
    set(${result} ${dirlist} PARENT_SCOPE)
endfunction()

# 统计源文件数量
function(count_source_files result curdir)
    file(GLOB_RECURSE sources
            ${curdir}/*.cpp
            ${curdir}/*.cxx
            ${curdir}/*.cc
    )
    list(LENGTH sources count)
    set(${result} ${count} PARENT_SCOPE)
endfunction()
